#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ibeacon.Resource", IsApplication=true)]

namespace ibeacon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bww = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hilton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iconHouse = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconThread = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconThreadTitle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int threadnation = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int BdTextView = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int BwwMap = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int HiltonMap = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int HiltonTextView = 2131230724;
			
			// aapt resource value: 0x7f080010
			public const int action_settings = 2131230736;
			
			// aapt resource value: 0x7f08000a
			public const int bluetoothToggleButton = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int chkDining = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int chkLodging = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int chkRetail = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int continueButton = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int imageView1 = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int notificationToggleButton = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int tvBluetooth = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int tvNotification = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int tvTitle = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int tvTutorial = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int tvTutorialTitle = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int buffalo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hilton = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Tutorial = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int settingsMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int BluetoothTitle = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int BwwInfo = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int CategoryTitle = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int NotificationTitle = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int Tutorial = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int TutorialTitle = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int hiltonInfo = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
